### ISSUE TITLE
您好,能上传一下数据库迁移文件吗

### ISSUE THREAD

**Issue by GOGOHQ** [zhaoshuxue/House#2]
您好,数据库里没有数据 能上传一下迁移文件吗

**Comment by shuxuecode** [comment]
项目根目录有数据库建表sql脚本文件

**Comment by GOGOHQ** [comment]
表里没数据呀






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 晚上6:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaoshuxue/House] 您好,能上传一下数据库迁移文件吗 (#2)





 
项目根目录有数据库建表sql脚本文件
